// Copyright 2015-2020 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

// TODO: make templates able to include other templates.
// e.g. "all" below should just say "core" and "boot". Use it to replace
// the old 'systemboot' template.
// Or just call it a day, now that we have the new directory structure, and dump the templates
// completely; that may be our best bet.
var templates = map[string][]string{
	"all": {
		"github.com/mvdan/u-root-coreutils/cmds/core/*",
		"github.com/mvdan/u-root-coreutils/cmds/boot/*boot*",
	},
	"boot": {
		"github.com/mvdan/u-root-coreutils/cmds/boot/*boot*",
	},
	// Absolutely everything, including experimental commands.
	"world": {
		"github.com/mvdan/u-root-coreutils/cmds/*/*",
	},
	// Core should be things you don't want to live without.
	"core": {
		"github.com/mvdan/u-root-coreutils/cmds/core/*",
	},
	// Minimal should be things you can't live without.
	"minimal": {
		"github.com/mvdan/u-root-coreutils/cmds/core/blkid",
		"github.com/mvdan/u-root-coreutils/cmds/core/cat",
		"github.com/mvdan/u-root-coreutils/cmds/core/chmod",
		"github.com/mvdan/u-root-coreutils/cmds/core/cmp",
		"github.com/mvdan/u-root-coreutils/cmds/core/cp",
		"github.com/mvdan/u-root-coreutils/cmds/core/date",
		"github.com/mvdan/u-root-coreutils/cmds/core/dd",
		"github.com/mvdan/u-root-coreutils/cmds/core/df",
		"github.com/mvdan/u-root-coreutils/cmds/core/dhclient",
		"github.com/mvdan/u-root-coreutils/cmds/core/dmesg",
		"github.com/mvdan/u-root-coreutils/cmds/core/echo",
		"github.com/mvdan/u-root-coreutils/cmds/core/elvish",
		"github.com/mvdan/u-root-coreutils/cmds/core/find",
		"github.com/mvdan/u-root-coreutils/cmds/core/free",
		"github.com/mvdan/u-root-coreutils/cmds/core/gpgv",
		"github.com/mvdan/u-root-coreutils/cmds/core/grep",
		"github.com/mvdan/u-root-coreutils/cmds/core/gzip",
		"github.com/mvdan/u-root-coreutils/cmds/core/hostname",
		"github.com/mvdan/u-root-coreutils/cmds/core/id",
		"github.com/mvdan/u-root-coreutils/cmds/core/init",
		"github.com/mvdan/u-root-coreutils/cmds/core/insmod",
		"github.com/mvdan/u-root-coreutils/cmds/core/io",
		"github.com/mvdan/u-root-coreutils/cmds/core/ip",
		"github.com/mvdan/u-root-coreutils/cmds/core/kexec",
		"github.com/mvdan/u-root-coreutils/cmds/core/kill",
		"github.com/mvdan/u-root-coreutils/cmds/core/ln",
		"github.com/mvdan/u-root-coreutils/cmds/core/losetup",
		"github.com/mvdan/u-root-coreutils/cmds/core/ls",
		"github.com/mvdan/u-root-coreutils/cmds/core/lsmod",
		"github.com/mvdan/u-root-coreutils/cmds/core/mkdir",
		"github.com/mvdan/u-root-coreutils/cmds/core/mknod",
		"github.com/mvdan/u-root-coreutils/cmds/core/mount",
		"github.com/mvdan/u-root-coreutils/cmds/core/msr",
		"github.com/mvdan/u-root-coreutils/cmds/core/mv",
		"github.com/mvdan/u-root-coreutils/cmds/core/pci",
		"github.com/mvdan/u-root-coreutils/cmds/core/ping",
		"github.com/mvdan/u-root-coreutils/cmds/core/printenv",
		"github.com/mvdan/u-root-coreutils/cmds/core/ps",
		"github.com/mvdan/u-root-coreutils/cmds/core/pwd",
		"github.com/mvdan/u-root-coreutils/cmds/core/readlink",
		"github.com/mvdan/u-root-coreutils/cmds/core/rm",
		"github.com/mvdan/u-root-coreutils/cmds/core/rmmod",
		"github.com/mvdan/u-root-coreutils/cmds/core/seq",
		"github.com/mvdan/u-root-coreutils/cmds/core/shutdown",
		"github.com/mvdan/u-root-coreutils/cmds/core/sleep",
		"github.com/mvdan/u-root-coreutils/cmds/core/sync",
		"github.com/mvdan/u-root-coreutils/cmds/core/tail",
		"github.com/mvdan/u-root-coreutils/cmds/core/tee",
		"github.com/mvdan/u-root-coreutils/cmds/core/truncate",
		"github.com/mvdan/u-root-coreutils/cmds/core/umount",
		"github.com/mvdan/u-root-coreutils/cmds/core/uname",
		"github.com/mvdan/u-root-coreutils/cmds/core/unshare",
		"github.com/mvdan/u-root-coreutils/cmds/core/wc",
		"github.com/mvdan/u-root-coreutils/cmds/core/wget",
		"github.com/mvdan/u-root-coreutils/cmds/core/which",
	},
	// embedded systems, like ARM based gadgets and SBCs
	"embedded": {
		"github.com/mvdan/u-root-coreutils/cmds/core/cat",
		"github.com/mvdan/u-root-coreutils/cmds/core/cp",
		"github.com/mvdan/u-root-coreutils/cmds/core/dd",
		"github.com/mvdan/u-root-coreutils/cmds/core/dhclient",
		"github.com/mvdan/u-root-coreutils/cmds/core/dmesg",
		"github.com/mvdan/u-root-coreutils/cmds/core/echo",
		"github.com/mvdan/u-root-coreutils/cmds/core/elvish",
		"github.com/mvdan/u-root-coreutils/cmds/core/free",
		"github.com/mvdan/u-root-coreutils/cmds/core/grep",
		"github.com/mvdan/u-root-coreutils/cmds/core/init",
		"github.com/mvdan/u-root-coreutils/cmds/core/insmod",
		"github.com/mvdan/u-root-coreutils/cmds/core/ip",
		"github.com/mvdan/u-root-coreutils/cmds/core/kexec",
		"github.com/mvdan/u-root-coreutils/cmds/core/ln",
		"github.com/mvdan/u-root-coreutils/cmds/core/ls",
		"github.com/mvdan/u-root-coreutils/cmds/core/mkdir",
		"github.com/mvdan/u-root-coreutils/cmds/core/mount",
		"github.com/mvdan/u-root-coreutils/cmds/core/netcat",
		"github.com/mvdan/u-root-coreutils/cmds/core/ping",
		"github.com/mvdan/u-root-coreutils/cmds/core/rm",
		"github.com/mvdan/u-root-coreutils/cmds/core/rmmod",
		"github.com/mvdan/u-root-coreutils/cmds/core/shutdown",
		"github.com/mvdan/u-root-coreutils/cmds/core/tail",
		"github.com/mvdan/u-root-coreutils/cmds/core/tee",
		"github.com/mvdan/u-root-coreutils/cmds/core/uname",
		"github.com/mvdan/u-root-coreutils/cmds/core/wget",
	},
	// coreboot-app minimal environment
	"coreboot-app": {
		"github.com/mvdan/u-root-coreutils/cmds/core/cat",
		"github.com/mvdan/u-root-coreutils/cmds/exp/cbmem",
		"github.com/mvdan/u-root-coreutils/cmds/core/chroot",
		"github.com/mvdan/u-root-coreutils/cmds/core/cp",
		"github.com/mvdan/u-root-coreutils/cmds/core/dd",
		"github.com/mvdan/u-root-coreutils/cmds/core/dhclient",
		"github.com/mvdan/u-root-coreutils/cmds/core/dmesg",
		"github.com/mvdan/u-root-coreutils/cmds/core/elvish",
		"github.com/mvdan/u-root-coreutils/cmds/core/find",
		"github.com/mvdan/u-root-coreutils/cmds/core/grep",
		"github.com/mvdan/u-root-coreutils/cmds/core/id",
		"github.com/mvdan/u-root-coreutils/cmds/core/init",
		"github.com/mvdan/u-root-coreutils/cmds/core/insmod",
		"github.com/mvdan/u-root-coreutils/cmds/core/ip",
		"github.com/mvdan/u-root-coreutils/cmds/core/kill",
		"github.com/mvdan/u-root-coreutils/cmds/core/ls",
		"github.com/mvdan/u-root-coreutils/cmds/core/mount",
		"github.com/mvdan/u-root-coreutils/cmds/core/pci",
		"github.com/mvdan/u-root-coreutils/cmds/core/ping",
		"github.com/mvdan/u-root-coreutils/cmds/core/ps",
		"github.com/mvdan/u-root-coreutils/cmds/core/pwd",
		"github.com/mvdan/u-root-coreutils/cmds/core/rm",
		"github.com/mvdan/u-root-coreutils/cmds/core/rmmod",
		"github.com/mvdan/u-root-coreutils/cmds/core/shutdown",
		"github.com/mvdan/u-root-coreutils/cmds/core/sshd",
		"github.com/mvdan/u-root-coreutils/cmds/core/switch_root",
		"github.com/mvdan/u-root-coreutils/cmds/core/tail",
		"github.com/mvdan/u-root-coreutils/cmds/core/tee",
		"github.com/mvdan/u-root-coreutils/cmds/core/uname",
		"github.com/mvdan/u-root-coreutils/cmds/core/wget",
	},
	"plan9": {
		"github.com/mvdan/u-root-coreutils/cmds/core/*",
	},
}
